services:
  tech-check-app:
    container_name: tech-check-container
    build:
      context: .
      dockerfile: Dockerfile
    image: tech-check:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: db-container
    image: mysql:8.0.37-debian
    environment:
      MYSQL_DATABASE: techcheck
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u ${MYSQL_USER} -p${MYSQL_PASSWORD} || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
