CREATE TABLE IF NOT EXISTS techcheck.users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(255) NOT NULL,
    balance DECIMAL
    );
CREATE TABLE IF NOT EXISTS techcheck.roles (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
    );
